name: Check Version
run-name: Check Version

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      code-changed: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Filter Changed Files
        uses: AurorNZ/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - 'src/**/*'
              - '!src/**/*.spec.*'

  check-version:
    needs: paths-filter
    if: needs.paths-filter.outputs.code-changed == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get New Version
        run: |
          new_version=$(npm pkg get version | xargs)
          echo "NEW=${new_version}" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get Main Version
        run: |
          main_version=$(npm pkg get version | xargs)
          echo "MAIN=${main_version}" >> $GITHUB_ENV

      - name: Compare Versions
        run: |
          if [[ ${{ env.NEW }} == ${{ env.MAIN }} ]]; then
            exit 1
          fi

      - name: Post PR Comment
        if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message: Please bump the version in package.json!
          refresh-message-position: true
          allow-repeats: true
