name: Publish

run-name: Publish Github pages

on:
  push:
    branches: ['main']

concurrency:
  group: 'githubpages'
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Package
        run: |
          npm ci
          npm run build

      - name: Create code coverage report
        run: npm run coverage

      - name: Set up example pages
        run: |
          cp ./dist/coordinate-conversion.umd.cjs ./example/bundle.js
          cp -r ./coverage ./example/coverage
          cd example
          touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: example
